/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#1B3270',
        blue: '#2952A3',
        'brand-blue': '#2952A3',
        'light-blue': '#7EB3E8',
        bg: '#F8FAFD',
        'app-bg': '#F8FAFD',
        surface: '#FFFFFF',
        'surface-hover': '#F0F4FF',
        border: '#E2E8F4',
        'border-color': '#E2E8F4',
        'border-strong': '#CBD5E9',
        'text-primary': '#1B3270',
        'text-secondary': '#4A5568',
        'text-muted': '#94A3B8',
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#EF4444',
        purple: '#7C3AED',
        'success-tint': '#F0FDF4',
        'warning-tint': '#FFFBEB',
        'danger-tint': '#FEF2F2',
        'blue-tint': '#EFF6FF',
        'primary-tint': '#F0F4FF',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        xs: '11px',
        sm: '12px',
        base: '13px',
        md: '14px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        card: '12px',
        btn: '8px',
        input: '8px',
      },
      boxShadow: {
        '2xs': '0 1px 2px rgba(27,50,112,0.05)',
        sm: '0 1px 3px rgba(27,50,112,0.06)',
        DEFAULT: '0 2px 8px rgba(27,50,112,0.08)',
        md: '0 2px 8px rgba(27,50,112,0.08)',
        lg: '0 4px 16px rgba(27,50,112,0.12)',
        subtle: '0 1px 4px rgba(27,50,112,0.08)',
      },
    },
  },
  plugins: [],
}
